### PR TITLE
added PSM functions

### PR DESCRIPTION
**Pull request by W-Mohammed**
Hi Khader,

Please review the branch and let me know if you are happy.
I have created new functions, including the run PSM model. The model now considers the intervention's costs according to the published treatment schedule.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by W-Mohammed** [comment]
Salam all!

I have added functions to:

- estimate the adverse events for the treatments and 
- calculate PPS treatment costs.

I have tested the functions and updated the documentation to make things more transparent.

I have PSA and one-way sensitivity analysis (OWSA) functions, which should be the end of my programming tasks.

I am still waiting for at least one of you to review the code and approve the pull request to consolidate it with the main branch on GitHub, which will allow the website to update. @Khader-Habash, I was expecting you to finish it by now.

**Comment by abeero126** [comment]
Thank you Wael for your email
We all were extremly busy with some urgent issues during the last 2 weeks
and we could not review the codes. This week we are planning to do the
reviosn. As models in R are still new for us we may require more time than
expected
Regards,
Abeer

**Comment by W-Mohammed** [comment]
Salam all, 

I am sorry to add to your work. I have just made significant changes to the model and its auxiliary functions.

I have just finished adding the PSA and One Way Sensitivity Analysis functions, including a tornado plotting function.

I have also added default data objects. These are lists of data that contain model parameters, PSA parameters and DSA parameters. They are all documented and start with the prefixes l_psm_, l_psa_ and l_dsa_, respectively. These data are from the Chinese data.

Moreover, I changed the inputs of the adverse events function from a list of lists to a list of scalars. If you have reviewed that function, you should spend a few minutes reviewing the updated function. This change makes the model more adaptable and accessible for handling the PSA and DSA functions. Another similar change was the output of the `run_psm` function, which is now a vector rather than a list for PSA and DSA reasons.

**Comment by Khader-Habash** [comment]
Hi  Wael,

Thanks for the update. I will start reviewing the code thoroughly this week.

I've quickly ran through the repository and wanted to verify if the updates
applied to the PSM file match those in the separate functions.

This is my first time reviewing code. I've cloned the repository to my
local device to start the review. Is this the right approach? Do you have
any technical tips that could help with the review process?

Best Regards.

**Comment by W-Mohammed** [comment]
Khader,

You have started things the right way. I can add a few pointers:

- use the "Git" tab in your RStudio to:
1. Switch to the right branch, and
2. Pull or get the latest changes in the respective branch.

You can find YouTube demos for how to switch branches and pull changes.

Remember to pull changes every time you open your RStudio for the latest
version of the code.

Regarding the code in the vignettes, this code is now obsolete and needs to
be updated.

**Review by Khader-Habash — APPROVED** [review]

**Pull request merged**
